<?php

/**
 * @file
 * oridomi.module
 */

/**
 * Implements hook_theme().
 */
function oridomi_theme() {
  return array(
    'oridomi' => array(
      'variables' => array('items' => array(), 'settings' => array()),
      'template' => 'theme/oridomi',
      'file' => 'theme/oridomi.theme.inc',
    ),
    'oridomi_list' => array(
      'variables' => array('items' => array(), 'settings' => array()),
      'file' => 'theme/oridomi.theme.inc',
    ),
    'oridomi_list_item' => array(
      'variables' => array('item' => array(), 'settings' => array()),
      'file' => 'theme/oridomi.theme.inc',
    ),
    'oridomi_admin_settings_form' => array(
      'render element' => 'form',
    ),
    'oridomi_admin_settings_form_fields' => array(
      'render element' => 'form',
    ),
  );
}

/**
 * Implements hook_library().
 */
function oridomi_library() {
  $library = libraries_get_path('oriDomi-master');

  $libraries['oridomi'] = array(
    'title' => 'OriDomi.js',
    'website' => 'http://oridomi.com/',
    'version' => array(),
    'js' => array(
      $library . '/oridomi.min.js' => array(
        'scope' => 'footer',
      ),
    ),
  );

  return $libraries;
}

/**
 * Loads parent instance settings.
 *
 * @param string $instance
 *  Settings group machine name.
 *
 * @param string $parent
 *  Parent HTML selector.
 */
function oridomi_initiate_instance($instance, $parent) {
  $version = variable_get('jquery_update_jquery_version', FALSE);
  if (!$version || $version == '1.10') {
    drupal_set_message(t('The installed jQuery version is not supported by Oridomi.'), 'error', FALSE);
  }

  // Include library.
  drupal_add_library('oridomi', 'oridomi');

  // Load parent settings from the instance id.
  $settings = _oridomi_return_parent_instance_settings($instance);

  // Provide alter for instance settings.
  drupal_alter('oridomi_settings', $settings, $instance);

  // Include instance settings.
  drupal_add_js(array(
    'oridomi' => array(
      $parent => array(
        'settings' => $settings,
        'views' => array(
          'ajax_pagination' => variable_get('oridomi_override_ajax_pagination_' . $instance)
        ),
      )
    ),
  ),
  'setting');
  drupal_add_js(drupal_get_path('module', 'oridomi') . '/includes/js/oridomi.settings.js', array('scope' => 'footer', 'type' => 'file'));
}

/**
 * Call to parent instance function
 */
module_load_include('inc','oridomi','settings/oridomi_plugin_parent.instance');

/**
 * Return array with key pair.
 */
function oridomi_instance_callback_list() {
  $instances = _oridomi_return_instances();

  // Format array as callback option list.
  foreach ($instances as $instance) {
    $content[$instance->name] = $instance->name;
  }

  return $content;
}

/**
 * Helper function, return active instances by name.
 */
function _oridomi_return_instances() {
  $query = 'SELECT name FROM {variable} WHERE name LIKE :name';
  $results = db_query($query, array(':name' => db_like('oridomi_settings_') . '%'))->fetchAll();

  return $results;
}
